[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[dev]
command = "npm run dev"
port = 5173
targetPort = 5173
publish = "dist"
functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
